-- general
require('keymappings')
require('settings')
require('colorscheme')

-- plugins
require('plugins')
require('plugins.nvim-tree')
require('plugins.nvim-lsp')
require('plugins.nvim-cmp')
require('plugins.git')
require('plugins.dashboard')
require('plugins.telescope')
require('plugins.project')
require('plugins.bufferline')
require('plugins.lightline')
require('plugins.colorizer')
require('plugins.markdown')
require('plugins.commenter')
require('plugins.latex')
require('plugins.vista')
require('plugins.autoformat')
